project:
  name: ORBIT # Name of project used to define input and output directories
  tissue_type: Lymph Node
  sample_type: Fine Needle Aspirate
  disease: Cancer
  PI: Shruthi Naik

seq:
  platform: Illumina NovaSeq X
  type: RNA-seq 
  end_type: Paired
  read_length: 100
  flowcell_id: 20260602_LH00761_0167_A22K7HFLT1
  lane: 1

run:
  sample_sheet: "sample_sheet.csv"
  ref_species: "Canis_lupus_familiarisgsd"
  ref_build: "UU_Cfam_GSD_1.0"
  ref_release: 116
  run_by: Elise Hachfeld

path: # Do NOT change these unless you are confident in directory structure and file locations.
  raw_data_dir: "data"
  reference_dir: "reference"
  results_dir: "results"
  report_dir: "report"

samtools:
  threads: 8
  
fastq:
  threads: 8

fastqc:
  threads: 8

fastp:
  threads: 8

kallisto:
  threads: 8

hisat2:
  threads: 8